### ISSUE TITLE
Pods

### ISSUE THREAD

**Issue by jpgruber** [bmbrina/BMCustomTableView#1]
Hi

You need two pods to install

target 'testCustom' do
  pod 'BMCustomTableView'
  pod 'RandomColorSwift'
end

Works great and looks really good.
Thanks.

**Comment by bmbrina** [comment]
Hi @jpgruber! Thanks for the support. I don't think I understood your question. The pod 'RandomColorSwift' is just an example of what you could do with this pod. So, if you could elaborate a little more I would be glad to help you.

**Comment by jpgruber** [comment]
Hi 
Thanks for responding.

I am new to CocoPods and to be able to build my solution to match yours I needed to reference both.

I may be wrong, but when I have been learning to use CocoPods, the first thing that I do is make my own project and try to replicate the example project using the Pod.  

When doing this for the first time you want the solution to match the behaviour and UI as seen in the example.  That way you can be certain that you have made it correctly. 

In this instance, the example needed the additional pod so I thought that I would communicate that.

Again, thanks for thinking this pod up as it helped me with my solution and learning.
